### ISSUE TITLE
Make requested changes

### ISSUE THREAD

**Issue by mateusriff** [robocin/robocin-website#22]
Feedbacks from RobôCIn's members requested a few changes. Implement them.

## Task

- Implement a few changes to each page.

### Home 
- [x] Enhance the quality of the group's logo in the navbar
- [x] Make adjustments to the banner so it is more responsive. **Note:** consider redesigning the banner altogether.
- [x] Remove modals that pop up on the activities section. They're bad!
- [x] Enhance responsivity of the sponsors section

### Categories
- [x] Add smooth scrolling 

### Research
- [x] Decrease the size of the publication card on notebook/desktop devices
